### ISSUE TITLE
Define rationale for Habitat type structure

### ISSUE THREAD

**Issue by asymmetric** [kinvolk/habitat-operator#182]
It's not totally clear at the moment why we put keys where we put them in the `Habitat` type.

* Is there a clear rationale?
* Would it make more sense to flatten it by removing the `Service` subtype?

I say this because I'm having trouble justifying why `configSecretName` should be under `Service`, rather than under `Habitat` directly.

Also, every time we have to add a new field, we should clearly know where.

---

I thought a clear rationale was: every field that represents a flag passed to the supervisor should go under `Service`. So for example: `--name`, `--topology`, `--bind`.

If that's true, than `configSecretName` should be move up.

But I wonder if such a rationale makes sense from the point of view of a user. It is not based on a logical grouping, rather it's based on inheritance (of the flags used by an existing tool).

**Comment by asymmetric** [comment]
I think we probably don't need to have a `service` key at all, i.e. we can just one level of depth.

**Comment by asymmetric** [comment]
@zeenix WDYT? Flattening the type layout will be a breaking change, and you seem to have strong feelings towards backwards compatibilty.

**Comment by LiliC** [comment]
@asymmetric Can you paste a sample manifest file of your idea for better clarity. 

Also as a side note according to the API version we are in beta not alpha, so these changes should have been done before that.

**Comment by asymmetric** [comment]
Basicaly,

```yaml
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: example-configured-habitat
spec:
  image: kinvolk/redis-hab
  count: 1
  service-name: db
  topology: standalone
  group: redisdb
  configSecretName: user-toml
```
